# Disable float control
stty -ixon

# Oh-my-zsh
ZSH=$HOME/.oh-my-zsh

ZSH_THEME="maran"

plugins=(git history)
source $ZSH/oh-my-zsh.sh





# JAVA_HOME
export JAVA_HOME="/usr/lib/jvm/java-8-oracle"
# Alias
alias tmux='tmux -2'
alias cdr= 'cd $projectRootDir'
alias mux= 'tmuxinator'
alias v='nvim'
alias vim='nvim'


# Load LSCOLORS
eval "$(dircolors -b ~/.dircolors)"

# FZF
export FZF_COMPLETION_TRIGGER='***'
export FZF_DEFAULT_COMMAND='ag -l --path-to-ignore ~/.ignore --nocolor --hidden -g ""'
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/lahann/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/lahann/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/home/lahann/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/lahann/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
# export PATH=/usr/local/cuda/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64
export CUDA_HOME=/usr/local/cuda

