# ~/.tmuxinator/mlpipe-config.yml

name: mlpipe-config
root: ~/data/versioning/gitlab/JohannesLahann/master/mlpipe/config

tmux_options: -2
windows:
  - vim: 
    - v 
  - shell:
    - alias cdr="cd $(pwd)"
  - sbt:
